on: [push]
jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
      - name: "setup depends"
        run: |
          sudo apt-get -y update
          sudo apt-get install -y build-essential git nasm
          echo "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"" >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install i686-elf-gcc
          echo $(ls)
          ls
          echo $(ls) > cat.txt
          cat dat.txt
      
      - name: "upload devOS.bin"
        uses: actions/upload-artifact@v2
        with:
          name: devOS.bin
          path: ./cat.txt
